-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Feb 18, 2025 at 02:14 PM
-- Server version: 10.4.10-MariaDB
-- PHP Version: 7.2.25

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dboprs`
--

-- --------------------------------------------------------

--
-- Table structure for table `tblemail_notif_contents`
--

DROP TABLE IF EXISTS `tblemail_notif_contents`;
CREATE TABLE IF NOT EXISTS `tblemail_notif_contents` (
  `row_id` int(11) NOT NULL AUTO_INCREMENT,
  `enc_process_id` int(11) NOT NULL,
  `enc_description` text NOT NULL,
  `enc_subject` text NOT NULL,
  `enc_process_owner` int(2) DEFAULT NULL,
  `enc_target_user` int(2) DEFAULT NULL,
  `enc_cc` text DEFAULT NULL,
  `enc_bcc` text DEFAULT NULL,
  `enc_content` text NOT NULL,
  `enc_user_group` varchar(64) NOT NULL,
  `enc_process_duration` varchar(16) DEFAULT NULL,
  `last_updated` datetime NOT NULL,
  PRIMARY KEY (`row_id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `tblemail_notif_contents`
--

INSERT INTO `tblemail_notif_contents` (`row_id`, `enc_process_id`, `enc_description`, `enc_subject`, `enc_process_owner`, `enc_target_user`, `enc_cc`, `enc_bcc`, `enc_content`, `enc_user_group`, `enc_process_duration`, `last_updated`) VALUES
(1, 1, 'Manuscript submission', 'NRCP Journal Publication : Acknowledgement of Manuscript Submission', 1, 1, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>[TITLE] </strong><strong>[FULL NAME],</strong><br><br>Thank you for submitting your manuscript. This will be processed and subjected to the next step.<br><br>You can track the status of your submission by logging in your account.<br><br>Click this link to login : <strong>[LINK]<br><br></strong>Should you have any further questions or require assistance, please do not hesitate to send us an email.\n<p>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph</p>\n<br>Best regards,<br><br>NRCP Online Peer Review System<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '0', '2025-01-29 18:58:36'),
(2, 2, 'Regret to inform about the failure to meet the criteria', 'NRCP Journal Publication : Technical Desk Editor Review', 5, 1, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear&nbsp;<strong>[TITLE] </strong><strong>[FULL NAME],</strong><br><br><br>Thank you for submitting your manuscript titled \"<strong>[MANUSCRIPT]</strong>\". We greatly appreciate your interest in sharing your valuable research with our publication.\n<p>After careful review, we regret to inform you that your submission does not meet the criteria required for publication in our journal at this time.</p>\n<p>We value the effort and dedication that went into your work and encourage you to consider revising your manuscript or submitting it to a journal better aligned with its focus. If you\'d like, we can provide additional feedback from our reviewers that might help you in this process.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph</p>\n<br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3', '0', '2025-01-24 21:13:04'),
(3, 3, 'Endorse tech review results to EIC', 'NRCP Journal Publication : Technical Desk Editor Revew Results', 5, 6, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>Editor-in-Chief,<br></strong><br>This is to inform you that the technical review for the manuscript \"<strong>[MANUSCRIPT]</strong>\" has been completed.\n<p>Click this link to login : <strong>[LINK]<br><br></strong>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph</p>\n<br><br>Best regards,<br><br>NRCP Online Peer Review System<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '7', '2025-01-29 19:18:16'),
(4, 4, 'Inform the author of the non-acceptance', 'NRCP Journal Publication : Notification of Non-acceptance', 6, 1, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear<strong> [TITLE] [FULL NAME],<br><br></strong><br>Thank you for submitting your manuscript, \"<strong>[MANUSCRIPT]</strong>\". After careful consideration, we regret to inform you that your submission has not been accepted for publication.\n<p>We sincerely appreciate your effort and contribution to the field and encourage you to consider submitting to other journals that may be better suited to your work.</p>\n<p>Thank you again for your interest in NRCP Journal Publication, and we wish you the best in your future research endeavors.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph</p>\n<br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '0', '2025-01-24 21:13:58'),
(5, 5, 'Review request', 'NRCP Journal Publication : Manuscript Review Request', 5, 16, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', '<strong>[FULL NAME]<br></strong><strong>[POSITION]</strong><br><strong>[AFFILIATION]</strong><br><strong>[ADDRESS]</strong> <br><br>Dear <strong>[TITLE]</strong> <strong>[LAST NAME]</strong>, <br><br><br>The NRCP Research Journal issued twice a year, features completed research projects of members of the National Research Council of the Philippines (NRCP), particularly those funded by the Council. This is one of NRCP\'s contributions to the body of knowledge in the realm of basic research which, we believe, paves the way for further research. <br><br>For [ISSUE], [VOLUME] ([YEAR]), we have selected manuscripts for possible publication and one of these is entitled \"<strong>[MANUSCRIPT]</strong>\". <br><br>In recognition of your expertise particularly in [SPECIALIZATION], may we request you to be a Reviewer of the above-mentioned manuscript. We are certain that as a Reviewer, you will render the paper a sound technical perspective worthy of publication in the NRCP Research Journal. Please refer to the attached Abstract to provide you with an overview of the paper. <br><br>[TIME] <br><br>With your acceptance of this invitation, we will send you the full manuscript, the manuscript evaluation form, and the Non-Disclosure Agreement (NDA) automatically once you log in as Reviewer. <br><br>[DUE] <br><br>[ACCEPT/DECLINE] <br><br>A modest token of appreciation will be given upon submission of your review.<br><br>Thank you for your favorable action on this request. <br><br>If you have already addressed this matter, kindly ignore or disregard this email.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '5', '2025-01-24 21:14:17'),
(6, 6, 'Decline Request', 'NRCP Journal Publication : Manuscript Review Request Declined', 16, 5, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>Technical Desk Editor</strong>,<br><br><br>Thank you for considering me to review the manuscript titled \"<strong>[MANUSCRIPT]</strong>\".\n<p>I regret to inform you that I am unable to accept this request at this time.</p>\n<p>Thank you for your understanding.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph</p>\n<br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '0', '2025-01-24 21:14:35'),
(7, 7, 'Accepted the review request', 'NRCP Journal Publication : Manuscript Review Request Accepted', 16, 5, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>[TITLE] </strong><strong>[FULL NAME]</strong>,<br><br><br>Thank you for accepting our invitation to be a reviewer. <br><br>Please login to your temporary account:<br><br>Username: <strong>[EMAIL]</strong><br>Password: <strong>[PASSWORD]</strong><br><br>Click this link to login : <strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '30', '2025-01-24 20:31:32'),
(8, 8, 'Remind to accept/decline review request', 'NRCP Journal Publication : Request for Manuscript Review', 0, 0, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>[TITLE] [FULL NAME],</strong><br><br><br>Please be reminded that there are only <strong>[DAYS]</strong> day/s left for you to <strong>[ACCEPT/DECLINE]</strong> the request for review on manuscript title \"<strong>[MANUSCRIPT]</strong>\" for publication in the NRCP Research Journal. <br><br>If you have already addressed this matter, kindly ignore or disregard this email.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3', '3', '2025-01-24 21:14:57'),
(9, 9, 'Remind to review manuscript', 'NRCP Journal Publication : Manuscript Review', 0, 0, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>[TITLE] [FULL NAME],</strong><br><br><br>May we remind you of your Review of the manuscript title \"<strong>[MANUSCRIPT]</strong>\" which is being considered for publication in the NRCP Research Journal. Given the deadline set, may we expect the accomplished evaluation/score sheet within the next <strong>[DAYS]</strong> day/s? <br><br>In case we do not hear from you, we shall automatically render your username and password deactivated.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3', '3', '2025-01-24 21:15:20'),
(10, 10, 'Lapsed Review Task', 'NRCP Journal Publication : Manuscript Review Lapse', 0, 5, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>[TITLE] [FULL NAME],</strong><br><br><br>We understand your busy schedule. We are looking forward to working with you on future issues.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best Regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:17:24'),
(11, 11, 'Submit the reviews of PeRev', 'NRCP Journal Publication : Manuscript Review Submitted', 0, 5, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>Technical Desk Editor</strong>,<br><br><br>We are pleased to inform you that the review for the manuscript titled <strong>\"[MANUSCRIPT]\"</strong> has been successfully submitted.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:15:44'),
(12, 12, 'Transmit the consolidated review', 'NRCP Journal Publication : Consolidation of Manuscript Review Results', 5, 17, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>Copy Editor</strong><strong>,<br></strong><br><br>We are pleased to inform you that the review results of the manuscript titled \"<strong>[MANUSCRIPT]</strong>\", including recommendations and feedback from all reviewers, have been successfully consolidated.\n<p>You may now review the consolidated report by logging into your account.</p>\n<br>Click this link to login: <strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '14', '2025-01-24 21:17:53'),
(13, 13, 'Inform the Author of manuscript the need to revise', 'NRCP Journal Publication : Manuscript Revision Requested', 0, 1, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>[TITLE] </strong><strong>[FULL NAME],<br><br><br></strong>This is to notify you that the review process for your manuscript titled <strong>\"[MANUSCRIPT]\"</strong> has been completed. Based on the reviewers\' evaluations, revisions are required before further processing.<br><br>Click this link to login: <strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:18:15'),
(14, 14, 'Submit author revision', 'NRCP Journal Publication : Manuscript Revision Submitted', 1, 5, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>Technical Desk Editor/Editor-in-Chief</strong><strong>,</strong><br><br><br>This is to notify you that the revised version of the manuscript titled <strong>\"[MANUSCRIPT]\"</strong> has been successfully submitted by the author.<br><br>Click this link to login: <strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '7', '2025-01-26 20:39:26'),
(15, 15, 'Endorse the proofread/edited manuscript', 'NRCP Journal Publication : Proofread/Revised Manuscript Endorsed', 1, 6, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>Editor-in-Chief</strong><strong>,</strong><br><br><br>This is to notify you that the proofread or revised manuscript titled <strong>\"[MANUSCRIPT]\"</strong> has been successfully endorsed and is now ready for the next stage in the process.<br><br>Click this link to login: <strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:18:51'),
(16, 16, 'Send edited manuscript for proofread', 'NRCP Journal Publication : Edited Manuscript Submitted for Proofreading', 17, 1, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear&nbsp;<strong>[TITLE] </strong><strong>[FULL NAME],</strong><br><br><br>This is to notify you that the edited manuscript titled <strong>\"[MANUSCRIPT]\"</strong> has been successfully submitted for proofreading.<br><br>Click this link to login: <strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:19:08'),
(17, 17, 'Submit final review of EIC', 'NRCP Journal Publication : Final Review Submitted', 6, 15, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear <strong>Layout Artist,<br></strong><br><br>This is to notify you that the final review of manuscript titled <strong>\"[MANUSCRIPT]\"</strong> has been successfully transmitted for further processing.<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:19:25'),
(18, 18, 'transmit the draft layout to EIC', 'NRCP Journal Publication : Draft Layout of Manuscript Transmitted', 15, 1, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear&nbsp;<strong>[TITLE] </strong><strong>[FULL NAME]</strong>,<br><br>This is to notify you that the draft layout of the manuscript titled <strong>\"[MANUSCRIPT]\"</strong> has been successfully transmitted.<br><br>Click this link to login: <strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:19:47'),
(19, 19, 'Informs author\'s that his/her manuscript is published to the eJournal website', 'NRCP Journal Publication : Manuscript is Published', 0, 1, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear&nbsp;<strong>[TITLE] </strong><strong>[FULL NAME]</strong>,<br><br>Please be informed that your submitted manuscript title \"<strong>[MANUSCRIPT]</strong>\" is now published to research journal wesbite.<br><br><strong>[LINK]</strong><br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>>', '3,5', '0', '2025-01-24 21:20:04'),
(20, 20, 'Certification template', 'Certification', 0, 0, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', '<div>This is to certify that [REVIEWER] was engaged by the National Research Council of the Philippines as REVIEWER of the NRCP-funded Project entitled \"[MANUSCRIPT]\" which is being considered for publication in the NRCP Research Journal.<br><br>[TITLE] [LAST NAME] was requested to do a review of the manuscript being an NRCP member whose expertise is in [SPECIALIZATION].<br><br></div>\n<div>This Certification was issued on [DATE].</div>', '3,5', '0', '2025-01-14 19:18:16'),
(21, 21, 'Reviewer will receive certification after submission of manusript review', 'NRCP Journal Publication : Certification', 0, 16, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear&nbsp;<strong>[TITLE]</strong> <strong>[FULL NAME],<br></strong><br><br>Thank you for reviewing the manuscript entitled \"[MANUSCRIPT]\". Please click the button below to download your certification.<br><br>[CERTIFICATION]<br><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '0', '2025-01-24 21:20:21'),
(22, 22, 'Endorsement of EIC to AssocEd', 'NRCP Journal Publication : Manuscript Review Request', 6, 11, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear&nbsp;<strong>Associate Editor,</strong><br><br>You have been assigned to review manuscript titled \"<strong>[MANUSCRIPT]</strong>\".<br>\n<p>Click this link to login : <strong>[LINK]<br></strong><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.</p>\n<br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Peer Review System<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-29 19:37:58'),
(23, 23, 'Enorsement of AssocEd to CluEd', 'NRCP Journal Publication : Manuscript Review Request', 11, 7, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', 'Dear&nbsp;<strong>Cluster Editor,</strong><br><br><br>You have been assigned to review manuscript titled \"<strong>[MANUSCRIPT]</strong>\".<br>\n<p>Click this link to login : <strong>[LINK]<br><br></strong>Should you have any further questions or require assistance, please do not hesitate to send us an email.</p>\n<br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph<br><br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:20:55'),
(24, 24, 'Endorsement for Peer Review', 'NRCP Journal Publication : Manuscript Review Request', 0, 5, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', '<p>Dear <strong>Technical Desk Editor</strong>,<br><br><br>We are pleased to inform you that the manuscript titled \"<strong>[MANUSCRIPT]</strong>\" has been accepted for endorsement to peer review.<br><br>Click this link to login : <strong>[LINK]<br></strong><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph</p>\n<br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:21:09'),
(40, 25, 'Inform\'s TeDeEd for a submitted manuscript', 'NRCP Journal Publication : Notification of Submitted Manuscript', 1, 5, 'gerard_balde@yahoo.com', 'gerard_balde@yahoo.com', '<p>Dear <strong>Technical Desk Editor</strong>,<br><br><br>We are pleased to inform you that the manuscript titled \"<strong>[MANUSCRIPT]</strong>\" has been submitted.<br><br>Click this link to login : <strong>[LINK]<br></strong><br>Should you have any further questions or require assistance, please do not hesitate to send us an email.<br><br>1. For publication-related matters - Lanie P. Manalo, Tel. No.: 837-6141. email: laniemanalo94@yahoo.com<br><br>2. For technical concerns - email: ejournal@nrcp.dost.gov.ph</p> <br><br>Best regards,<br><br>NRCP Online Research Journal<br><br><br><em>** THIS IS AN AUTOMATED MESSAGE PLEASE DO NOT REPLY **</em>', '3,5', '3', '2025-01-24 21:21:09');

-- --------------------------------------------------------

--
-- Table structure for table `tblprocess_status`
--

DROP TABLE IF EXISTS `tblprocess_status`;
CREATE TABLE IF NOT EXISTS `tblprocess_status` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `ps_man_id` int(11) NOT NULL,
  `ps_processor_id` varchar(64) DEFAULT NULL,
  `ps_role_id` int(11) DEFAULT NULL,
  `ps_status` int(1) DEFAULT 0 COMMENT '0-No action yet 1-processed',
  `ps_duration` int(3) NOT NULL,
  `ps_action_date` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=29 DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `tblstatus_types`
--

DROP TABLE IF EXISTS `tblstatus_types`;
CREATE TABLE IF NOT EXISTS `tblstatus_types` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
  `status_desc` varchar(255) DEFAULT NULL,
  `status_id` int(2) DEFAULT NULL,
  `status_class` char(16) NOT NULL,
  `status` int(11) NOT NULL DEFAULT 1 COMMENT '0-disabled 1-enabled',
  `created_at` datetime DEFAULT NULL COMMENT 'Create Time',
  `last_updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=20 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `tblstatus_types`
--

INSERT INTO `tblstatus_types` (`id`, `status_desc`, `status_id`, `status_class`, `status`, `created_at`, `last_updated`) VALUES
(1, 'On-review: TeDeEd', 1, 'warning', 1, NULL, '2024-12-29 22:33:52'),
(2, 'On-review: EIC', 2, 'primary', 1, NULL, NULL),
(3, 'On-review: AssocEd', 3, 'primary', 1, NULL, NULL),
(4, 'On-review: CluEd', 4, 'primary', 1, NULL, NULL),
(5, 'On-review: Peer', 5, 'primary', 1, NULL, NULL),
(6, 'Review Consolidation: TeDeEd', 6, 'primary', 1, NULL, NULL),
(7, 'Proofread: CopEd', 7, 'primary', 1, NULL, NULL),
(8, 'Final Review: EIC', 8, 'primary', 1, NULL, NULL),
(9, 'Proofread: Author', 9, 'dark', 1, NULL, NULL),
(10, 'Revision: Author', 10, 'dark', 1, NULL, NULL),
(11, 'Layout: LayArt', 11, 'dark', 1, NULL, NULL),
(12, 'Final Approval: EIC', 12, 'dark', 1, NULL, NULL),
(13, 'Publication: queue', 13, 'success', 1, NULL, NULL),
(14, 'Rejected', 14, 'danger', 1, NULL, NULL),
(15, 'Endorsement to Peer', 15, 'primary', 1, NULL, NULL),
(16, 'Published', 16, 'success', 1, NULL, NULL),
(17, 'Revised', 17, 'secondary', 1, NULL, NULL),
(19, 'Final Proofread: Author', 18, 'primary', 1, NULL, NULL);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
